version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "[GHA] "
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "[Docker] "
  - package-ecosystem: "gitsubmodule"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "[HOPM] "
