name: Docker Image CI

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: adamus1red/hopm,${{ secrets.DOCKER_ALT }}
          sep-tags: ','
          tags: |
            type=schedule
            type=ref,event=pr
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},prefix=v
      #-
        #name: Available platforms
        #run: for f in ${{ steps.meta.outputs.tags }}; do echo ${f}; done
        
      - name: Docker multi-arch Build
        run: |
          IFS=', ' read -r -a tags <<< "${{ steps.meta.outputs.tags }}"; for tag in ${tags[@]}; do docker build -t ${tag} --platform linux/amd64,linux/386,linux/arm64,linux/ppc64le,linux/arm/v7,linux/arm/v6 .; done
