name: Docker Image CI

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: adamus1red/hopm,${{ secrets.DOCKER_ALT }}
          tags: |
            type=schedule
            type=ref,event=pr
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},prefix=v
      -
        name: Available platforms
        run: for f in ${{ steps.meta.outputs.tags }}; do echo ${f}; done
        
      - name: Docker multi-arch Build
        run: |
          for tag in ${{ steps.meta.outputs.tags }}; do \
            docker build -t ${tag} --platform linux/amd64,linux/386,linux/arm64,linux/ppc64le,linux/arm/v7,linux/arm/v6 . \
          done
